"""Realistic dummy catalogs for local/UI testing (synthetic, no real PII)."""

from __future__ import annotations

PEOPLE: list[tuple[str, str, str]] = [
    ("Ahmad Raza", "ahmad.raza@eazisols.example", "pm"),
    ("Fatima Khan", "fatima.khan@eazisols.example", "tech_lead"),
    ("Usman Ali", "usman.ali@eazisols.example", "qa_lead"),
    ("Sara Ahmed", "sara.ahmed@eazisols.example", "ba"),
    ("Bilal Hassan", "bilal.hassan@eazisols.example", "developer"),
    ("Ayesha Malik", "ayesha.malik@eazisols.example", "designer"),
    ("Omar Sheikh", "omar.sheikh@eazisols.example", "devops"),
    ("Hina Qureshi", "hina.qureshi@eazisols.example", "client_success"),
    ("Zainab Tariq", "zainab.tariq@eazisols.example", "sales"),
    ("Hamza Iqbal", "hamza.iqbal@eazisols.example", "architect"),
    ("Nadia Farooq", "nadia.farooq@eazisols.example", "scrum_master"),
    ("Ali Rehman", "ali.rehman@eazisols.example", "security"),
    ("Maryam Siddiqui", "maryam.siddiqui@eazisols.example", "dba"),
    ("Faisal Mehmood", "faisal.mehmood@eazisols.example", "mobile_dev"),
    ("Sana Javed", "sana.javed@eazisols.example", "data_engineer"),
    ("Kamran Butt", "kamran.butt@eazisols.example", "support"),
    ("Iqra Naveed", "iqra.naveed@eazisols.example", "finance"),
    ("Danish Chaudhry", "danish.chaudhry@eazisols.example", "hr"),
    ("Rabia Anwar", "rabia.anwar@eazisols.example", "intern"),
    ("Taimoor Shah", "taimoor.shah@eazisols.example", "cto"),
]

ROLES: list[tuple[str, str]] = [
    ("pm", "Project Manager"),
    ("tech_lead", "Technical Lead"),
    ("qa_lead", "QA Lead"),
    ("ba", "Business Analyst"),
    ("developer", "Software Engineer"),
    ("designer", "Product Designer"),
    ("devops", "DevOps Engineer"),
    ("client_success", "Client Success Manager"),
    ("sales", "Business Development"),
    ("architect", "Solution Architect"),
    ("scrum_master", "Scrum Master"),
    ("security", "Security Engineer"),
    ("dba", "Database Administrator"),
    ("mobile_dev", "Mobile Engineer"),
    ("data_engineer", "Data Engineer"),
    ("support", "Support Engineer"),
    ("finance", "Finance Partner"),
    ("hr", "People Operations"),
    ("intern", "Engineering Intern"),
    ("cto", "Chief Technology Officer"),
]

DEPARTMENTS: list[tuple[str, str]] = [
    ("delivery", "Delivery"),
    ("engineering", "Engineering"),
    ("quality", "Quality"),
    ("sales", "Sales"),
    ("people", "People"),
    ("finance", "Finance"),
    ("security", "Security"),
    ("platform", "Platform"),
]

TEAMS: list[tuple[str, str, str]] = [
    ("portal_squad", "Portal Squad", "delivery"),
    ("claims_squad", "Claims Squad", "delivery"),
    ("mobile_squad", "Mobile Squad", "engineering"),
    ("platform_squad", "Platform Squad", "platform"),
    ("qa_guild", "QA Guild", "quality"),
    ("ba_pod", "BA Pod", "delivery"),
    ("data_squad", "Data Squad", "engineering"),
    ("support_desk", "Support Desk", "delivery"),
    ("sales_bd", "Sales BD", "sales"),
    ("design_studio", "Design Studio", "delivery"),
    ("secops", "SecOps", "security"),
    ("sre", "SRE", "platform"),
    ("intern_lab", "Intern Lab", "engineering"),
    ("architecture", "Architecture", "engineering"),
    ("pmo", "PMO", "delivery"),
    ("client_success", "Client Success", "sales"),
    ("integrations", "Integrations", "platform"),
    ("ai_ops", "AI Operations", "engineering"),
    ("release_train", "Release Train", "delivery"),
    ("ux_research", "UX Research", "delivery"),
]

CLIENTS: list[tuple[str, str, str, str]] = [
    ("hbl", "Habib Bank Limited", "banking", "https://www.hbl.com"),
    ("packages", "Packages Limited", "manufacturing", "https://www.packages.com.pk"),
    ("nishat", "Nishat Mills Limited", "textiles", "https://www.nishatmillsltd.com"),
    ("khaadi", "Khaadi Corporation", "retail", "https://www.khaadi.com"),
    ("careem", "Careem Networks FZ LLC", "mobility", "https://www.careem.com"),
    ("jazz", "Pakistan Mobile Communications", "telecom", "https://www.jazz.com.pk"),
    ("engro", "Engro Corporation", "energy", "https://www.engro.com"),
    ("tmfb", "Telenor Microfinance Bank", "fintech", "https://www.telenorbank.pk"),
    ("daraz", "Daraz Pakistan", "ecommerce", "https://www.daraz.pk"),
    ("systems", "Systems Limited", "it_services", "https://www.systemsltd.com"),
    ("nestle", "Nestle Pakistan Limited", "fmcg", "https://www.nestle.pk"),
    ("pso", "Pakistan State Oil", "energy", "https://www.psopk.com"),
    ("meezan", "Meezan Bank Limited", "banking", "https://www.meezanbank.com"),
    ("atlas", "Atlas Honda Limited", "automotive", "https://www.atlashonda.com.pk"),
    ("unilever", "Unilever Pakistan Limited", "fmcg", "https://www.unilever.pk"),
    ("fatima", "Fatima Fertilizer Company", "agriculture", "https://www.fatima-group.com"),
    ("silkbank", "Silkbank Limited", "banking", "https://www.silkbank.com.pk"),
    ("foodpanda", "Foodpanda Pakistan", "delivery", "https://www.foodpanda.pk"),
    ("lums", "Lahore University of Management Sciences", "education", "https://lums.edu.pk"),
    ("pitb", "Punjab Information Technology Board", "public_sector", "https://pitb.gov.pk"),
]

CONTACTS: list[tuple[str, str, str]] = [
    ("Nida Hassan", "Head of Digital", "decision_maker"),
    ("Imran Qadir", "IT Director", "technical"),
    ("Saima Bukhari", "Procurement Lead", "commercial"),
    ("Junaid Akhtar", "Product Owner", "technical"),
    ("Rabia Gul", "Operations Manager", "decision_maker"),
    ("Shahzad Malik", "CISO", "technical"),
    ("Hira Naeem", "Finance Controller", "commercial"),
    ("Tariq Mehmood", "Plant Manager", "decision_maker"),
    ("Amina Shah", "CX Lead", "general"),
    ("Waqas Anjum", "Engineering Manager", "technical"),
    ("Farah Jamil", "Brand Manager", "commercial"),
    ("Adnan Rauf", "Fleet Manager", "decision_maker"),
    ("Mehwish Ali", "Compliance Officer", "commercial"),
    ("Haroon Saeed", "Dealer Principal", "decision_maker"),
    ("Zara Iqbal", "Trade Marketing", "commercial"),
    ("Noman Ashraf", "HSE Lead", "technical"),
    ("Saba Rehman", "SME Banking Head", "decision_maker"),
    ("Yasir Khan", "Partner Success", "general"),
    ("Dr. Lubna Aziz", "Registrar", "decision_maker"),
    ("Asad Cheema", "Director e-Services", "technical"),
]

PROJECTS: list[tuple[str, str]] = [
    ("HBL-PORTAL", "HBL Customer Portal Redesign"),
    ("PKG-SCM", "Packages Supply Chain Visibility"),
    ("NSH-MES", "Nishat Production Floor MES"),
    ("KHD-OMNI", "Khaadi Omnichannel Retail"),
    ("CRM-OPS", "Careem Driver Ops Console"),
    ("JAZ-API", "Jazz Partner API Gateway"),
    ("ENG-MAINT", "Engro Plant Maintenance Desk"),
    ("TMF-AGENT", "TMFB Agent Banking App"),
    ("DRZ-SELL", "Daraz Seller Onboarding"),
    ("SYS-PMO", "Systems Internal PMO"),
    ("NST-DIST", "Nestle Distributor Portal"),
    ("PSO-FLEET", "PSO Fleet Card Platform"),
    ("MZN-TRADE", "Meezan Islamic Trade Finance"),
    ("ATL-WARR", "Atlas Honda Dealer Warranty"),
    ("UL-PROMO", "Unilever Trade Promotion"),
    ("FTM-HSE", "Fatima Safety Incident Desk"),
    ("SLK-SME", "Silkbank SME Lending"),
    ("FPD-REST", "Foodpanda Restaurant Partner Desk"),
    ("LMS-CAMP", "LUMS Campus Services"),
    ("PIT-CITZ", "PITB Citizen Services"),
]

QUERIES: list[tuple[str, str]] = [
    ("Need a customer portal with biometric login", "We want retail customers to open accounts digitally with NADRA verification."),
    ("Warehouse barcode scanning on Android", "Our Lahore plant still uses paper GRNs. Need offline-capable scanning."),
    ("Loom downtime dashboard", "Supervisors need live OEE and shift handover notes."),
    ("Unify web and store inventory", "Click-and-collect fails when store stock is stale."),
    ("Driver incentive calculator", "Weekly bonuses are calculated in Excel and disputed."),
    ("Expose prepaid APIs to aggregators", "Partners need sandboxed REST with usage caps."),
    ("CMMS for urea plant", "Work orders, spare parts, and permit-to-work in one place."),
    ("Agent onboarding KYC", "Branchless agents wait days for compliance clearance."),
    ("Seller document vault", "CNIC and NTN uploads keep getting lost in email."),
    ("Resource forecast for 40 squads", "PMO cannot see bench vs allocated capacity."),
    ("Distributor claim workflow", "Damaged-goods claims take three weeks."),
    ("Fleet card dispute desk", "Merchants raise chargebacks with photos."),
    ("Murabaha workflow", "Shariah reviewers need a four-eye check."),
    ("Warranty claim photos", "Dealers submit claims with chassis numbers."),
    ("Promo accrual engine", "Trade spend is booked late every quarter."),
    ("Incident reporting on mobile", "Contractors must log near-misses in Urdu and English."),
    ("SME loan origination", "Relationship managers still use shared drives."),
    ("Restaurant menu sync", "Item availability is wrong during peak hours."),
    ("Hostel room booking", "Students queue at the office every semester."),
    ("Birth certificate e-service", "Citizens want status tracking after submission."),
]

SKILLS: list[tuple[str, str, str]] = [
    ("python", "Python", "engineering"),
    ("typescript", "TypeScript", "engineering"),
    ("react", "React", "engineering"),
    ("fastapi", "FastAPI", "engineering"),
    ("postgresql", "PostgreSQL", "engineering"),
    ("nextjs", "Next.js", "engineering"),
    ("temporal", "Temporal", "platform"),
    ("langgraph", "LangGraph", "ai"),
    ("qa_automation", "QA Automation", "quality"),
    ("manual_qa", "Manual QA", "quality"),
    ("figma", "Figma", "design"),
    ("android", "Android", "engineering"),
    ("ios", "iOS", "engineering"),
    ("devops_aws", "AWS DevOps", "platform"),
    ("security_review", "Security Review", "security"),
    ("business_analysis", "Business Analysis", "delivery"),
    ("project_management", "Project Management", "delivery"),
    ("data_modeling", "Data Modeling", "engineering"),
    ("technical_writing", "Technical Writing", "delivery"),
    ("client_facilitation", "Client Facilitation", "sales"),
]

PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("identity.read", "identity", "read", "Read identity"),
    ("identity.write", "identity", "write", "Write identity"),
    ("clients.read", "clients", "read", "Read clients"),
    ("clients.write", "clients", "write", "Write clients"),
    ("queries.read", "queries", "read", "Read queries"),
    ("queries.write", "queries", "write", "Write queries"),
    ("projects.read", "projects", "read", "Read projects"),
    ("projects.write", "projects", "write", "Write projects"),
    ("tickets.read", "tickets", "read", "Read tickets"),
    ("tickets.write", "tickets", "write", "Write tickets"),
    ("qa.read", "qa", "read", "Read QA"),
    ("qa.write", "qa", "write", "Write QA"),
    ("releases.read", "releases", "read", "Read releases"),
    ("releases.approve", "releases", "approve", "Approve releases"),
    ("governance.read", "governance", "read", "Read governance"),
    ("governance.approve", "governance", "approve", "Approve governance"),
    ("security.read", "security", "read", "Read security"),
    ("security.write", "security", "write", "Write security"),
    ("integrations.read", "integrations", "read", "Read integrations"),
    ("integrations.write", "integrations", "write", "Write integrations"),
]

ADRS: list[tuple[str, str]] = [
    ("ADR-001", "PostgreSQL as system of record"),
    ("ADR-002", "FastAPI owns deterministic rules"),
    ("ADR-003", "Temporal for long-running waits"),
    ("ADR-004", "LangGraph for bounded AI drafts"),
    ("ADR-005", "Row-level security by organization"),
    ("ADR-006", "No raw secrets in source or logs"),
    ("ADR-007", "Human approval for production deploy"),
    ("ADR-008", "Immutable approved requirements"),
    ("ADR-009", "pgvector only for retrieval"),
    ("ADR-010", "SNS/SQS for async events"),
    ("ADR-011", "Next.js desks over FastAPI"),
    ("ADR-012", "Synthetic data in development"),
    ("ADR-013", "Gmail send only after review"),
    ("ADR-014", "Jira push only after approval"),
    ("ADR-015", "Audit log is append-only"),
    ("ADR-016", "Must-have traceability before release"),
    ("ADR-017", "QA rejection returns to delivery loop"),
    ("ADR-018", "Pilot before production sign-off"),
    ("ADR-019", "Capacity allocation cannot exceed 100%"),
    ("ADR-020", "Client data never crosses tenants"),
]

KNOWLEDGE: list[tuple[str, str]] = [
    ("KB-ONB", "Client onboarding playbook"),
    ("KB-SLA", "Query SLA handling"),
    ("KB-SRS", "SRS baseline checklist"),
    ("KB-QA", "QA rejection loop"),
    ("KB-REL", "Release evidence pack"),
    ("KB-SEC", "PII handling notes"),
    ("KB-DEP", "Staging deploy steps"),
    ("KB-FU", "Follow-up escalation"),
    ("KB-CR", "Change request thresholds"),
    ("KB-ADR", "ADR writing guide"),
    ("KB-CAP", "Capacity planning"),
    ("KB-INT", "Integration credential refs"),
    ("KB-GM", "Gmail draft review"),
    ("KB-JIRA", "Jira issue mapping"),
    ("KB-UAT", "UAT sample scripts"),
    ("KB-PILOT", "Pilot user training"),
    ("KB-DR", "DR restore order"),
    ("KB-BUG", "Severity vs release block"),
    ("KB-COMMS", "Client email tone"),
    ("KB-TRACE", "Must-have coverage"),
]

BUGS: list[str] = [
    "Portal session drops after NADRA callback",
    "GRN scan duplicates when offline queue replays",
    "OEE chart shows next-shift data",
    "Click-and-collect reserves sold-out SKU",
    "Bonus calculator ignores public holidays",
    "Partner sandbox leaks production rate limits",
    "Work order cannot attach permit PDF",
    "KYC status stuck in submitted",
    "Seller CNIC preview is blank on Safari",
    "PMO forecast ignores leave",
    "Claim photos rotate 90 degrees",
    "Chargeback SLA clock ignores weekends",
    "Murabaha step skips Shariah reviewer",
    "Chassis OCR misreads letter O as 0",
    "Promo accrual double-counts returns",
    "Near-miss form rejects Urdu digits",
    "SME application PDF missing signature page",
    "Menu sync lags 12 minutes",
    "Hostel booking allows overlapping dates",
    "Citizen tracking ID not emailed",
]

NOTIFICATIONS: list[str] = [
    "Follow-up due tomorrow for HBL portal kickoff",
    "QA rejected ticket HBL-PORTAL-12",
    "Release REL-HBL-1.0 awaiting CAB",
    "Capacity for Portal Squad exceeds 90%",
    "New query from Packages Limited",
    "ADR-007 proposed for production gate",
    "Legal hold placed on PSO dispute docs",
    "Pilot users pending training",
    "Gmail draft ready for review",
    "Jira push blocked until approval",
    "Must-have REQ-HBL-01 missing test evidence",
    "Client Hina requested status report",
    "Backup confirmation missing for REL-JAZ-1.0",
    "Leave overlap on Engro squad next week",
    "UAT script PIT-CITZ failed login step",
    "Security incident INC-014 still open",
    "Change request CR-KHD-03 submitted",
    "Deployment to staging succeeded",
    "Overdue follow-up on Meezan trade finance",
    "Weekly digest of open approvals",
]

AGENT_CODES = [
    "query_intake_agent",
    "requirements_clarifier",
    "roadmap_planner",
    "ticket_triage_agent",
    "qa_review_assistant",
    "status_report_drafter",
]

IDENTITY_AGENT_KEYS = [
    "query_intake_agent",
    "requirements_clarifier",
    "roadmap_planner",
    "ticket_triage_agent",
    "qa_review_assistant",
    "status_report_drafter",
    "followup_chaser",
    "approval_summarizer",
    "release_notes_agent",
    "bug_classifier",
    "capacity_advisor",
    "knowledge_indexer",
    "security_reviewer",
    "client_comms_drafter",
    "test_case_suggester",
    "change_impact_agent",
    "pilot_readiness_agent",
    "audit_narrator",
    "inbox_prioritizer",
    "closure_checklist_agent",
]

WORKFLOW_CODES = [
    "query_intake",
    "requirement_clarification",
    "project_handover",
    "assignment_ack",
    "blocker_resolution",
    "qa_rejection_loop",
    "client_status_report",
    "change_request_flow",
    "deployment_approval",
    "project_closure",
    "approval_gate_wait",
    "followup_escalation",
]

CONFIG_WORKFLOW_CODES = [
    *WORKFLOW_CODES,
    "ticket_lifecycle",
    "release_gate",
    "incident_response",
    "leave_coverage",
    "document_review",
    "uat_signoff",
    "support_handover",
    "commercial_close",
]

QUERY_SOURCES = [
    ("website_form", "Website enquiry form", "web"),
    ("inbound_email", "Inbound sales inbox", "email"),
    ("whatsapp_bd", "WhatsApp business development", "whatsapp"),
    ("linkedin_inmail", "LinkedIn InMail", "linkedin"),
    ("referral_partner", "Partner referral", "referral"),
    ("phone_reception", "Reception phone log", "phone"),
    ("expo_lahore", "Lahore tech expo booth", "event"),
    ("expo_karachi", "Karachi fintech meetup", "event"),
    ("rfp_portal", "Public RFP portal", "web"),
    ("existing_client", "Existing client expansion", "account"),
    ("support_escalation", "Support-to-sales escalation", "support"),
    ("cold_outbound", "Outbound BD campaign", "outbound"),
    ("google_ads", "Google Ads landing page", "web"),
    ("facebook_lead", "Facebook lead form", "social"),
    ("walk_in", "Office walk-in", "in_person"),
    ("tender_pk", "Pakistan tender notice", "tender"),
    ("alumni_network", "Alumni referral", "referral"),
    ("webinar_qna", "Product webinar Q&A", "event"),
    ("slack_community", "Community Slack intro", "chat"),
    ("partner_bank", "Banking partner desk", "partner"),
]

APPROVAL_ACTIONS = [
    "srs.baseline.approve",
    "release.approve",
    "change.request.approve",
    "milestone.approve",
    "deployment.production.approve",
    "discount.commercial.approve",
    "pilot.plan.approve",
    "document.external.approve",
    "bug.defer.approve",
    "exception.risk.approve",
    "knowledge.publish.approve",
    "integration.connect.approve",
    "legal.hold.release",
    "uat.exit.approve",
    "project.closure.approve",
    "resource.overallocate.approve",
    "timeline.commit.approve",
    "security.exception.approve",
    "backup.skip.approve",
    "client.delivery.accept",
]
