# Updates LAN IP into .env / apps/web/.env.local and regenerates Docs/local-wifi-server-status.md
# Usage (repo root):
#   powershell -ExecutionPolicy Bypass -File scripts/update-lan-server.ps1

[CmdletBinding()]
param(
    [string]$RepoRoot = "",
    [string]$VercelOrigin = "https://multi-agent-sms.vercel.app",
    [int]$ApiPort = 8000,
    [int]$WebPort = 3000
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not $RepoRoot) {
    $scriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $RepoRoot = (Resolve-Path (Join-Path $scriptDir "..")).Path
}

function Get-LanIPv4 {
    $candidates = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object {
            $_.IPAddress -notlike "127.*" -and
            $_.IPAddress -notlike "169.254.*" -and
            $_.PrefixOrigin -ne "WellKnown"
        } |
        Sort-Object -Property @{
            Expression = {
                $adapter = Get-NetAdapter -InterfaceIndex $_.InterfaceIndex -ErrorAction SilentlyContinue
                if ($adapter -and $adapter.Status -eq "Up" -and ($adapter.Name -match "Wi-?Fi|Wireless|WLAN")) { 0 }
                elseif ($adapter -and $adapter.Status -eq "Up") { 1 }
                else { 2 }
            }
        }, InterfaceMetric

    if (-not $candidates) {
        throw "No usable LAN IPv4 address found. Connect to Wi-Fi and retry."
    }

    return $candidates[0].IPAddress
}

function Upsert-EnvLine {
    param(
        [string]$Path,
        [string]$Key,
        [string]$Value
    )

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }

    $lines = @()
    if (Test-Path $Path) {
        $lines = Get-Content -Path $Path -ErrorAction Stop
    }

    $pattern = "^\s*$([regex]::Escape($Key))\s*="
    $replaced = $false
    $out = foreach ($line in $lines) {
        if ($line -match $pattern) {
            $replaced = $true
            "$Key=$Value"
        }
        else {
            $line
        }
    }

    if (-not $replaced) {
        if ($out.Count -gt 0 -and $out[-1].Trim() -ne "") {
            $out += ""
        }
        $out += "$Key=$Value"
    }

    Set-Content -Path $Path -Value $out -Encoding UTF8
}

$lanIp = Get-LanIPv4
$apiBase = "http://${lanIp}:${ApiPort}"
$webBase = "http://${lanIp}:${WebPort}"
$stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$corsOrigins = @(
    "http://localhost:${WebPort}",
    "http://127.0.0.1:${WebPort}",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    $webBase,
    $VercelOrigin
) -join ","

$rootEnv = Join-Path $RepoRoot ".env"
$webEnv = Join-Path $RepoRoot "apps\web\.env.local"
$statusPath = Join-Path $RepoRoot "Docs\local-wifi-server-status.md"

if (-not (Test-Path $rootEnv)) {
    $example = Join-Path $RepoRoot ".env.example"
    if (Test-Path $example) {
        Copy-Item $example $rootEnv
        Write-Host "Created .env from .env.example"
    }
    else {
        New-Item -ItemType File -Path $rootEnv | Out-Null
    }
}

if (-not (Test-Path $webEnv)) {
    $webExample = Join-Path $RepoRoot "apps\web\.env.example"
    if (Test-Path $webExample) {
        Copy-Item $webExample $webEnv
        Write-Host "Created apps/web/.env.local from .env.example"
    }
}

Upsert-EnvLine -Path $rootEnv -Key "MASMS_CORS_ORIGINS" -Value $corsOrigins
# Keep local Next on same-origin rewrite → 127.0.0.1:8000 (stable for localhost:3000).
# Vercel Wi-Fi backend settings are written only to Docs/vercel-lan.env.txt.
Upsert-EnvLine -Path $webEnv -Key "MASMS_API_ORIGIN" -Value "http://127.0.0.1:${ApiPort}"
# Remove direct-mode keys from local env if present (they break localhost when stale).
if (Test-Path $webEnv) {
    $filtered = Get-Content $webEnv | Where-Object {
        $_ -notmatch '^\s*NEXT_PUBLIC_API_BASE_URL\s*=' -and
        $_ -notmatch '^\s*NEXT_PUBLIC_API_USE_DIRECT\s*='
    }
    Set-Content -Path $webEnv -Value $filtered -Encoding UTF8
}

$vercelEnvPath = Join-Path $RepoRoot "Docs\vercel-lan.env.txt"
$vercelEnvBody = @"
# Paste into Vercel → Project → Settings → Environment Variables, then Redeploy.
# Regenerated $stamp for LAN $lanIp
NEXT_PUBLIC_API_USE_DIRECT=true
NEXT_PUBLIC_API_BASE_URL=$apiBase
"@
Set-Content -Path $vercelEnvPath -Value $vercelEnvBody -Encoding UTF8

$status = @"
# Local Wi‑Fi backend status (for Vercel live app)

Auto-generated by ``scripts/update-lan-server.ps1``. Do not edit by hand.

| Field | Value |
|---|---|
| Updated | $stamp |
| LAN IPv4 | ``$lanIp`` |
| Vercel live UI | [$VercelOrigin/queries]($VercelOrigin/queries) |
| PC API (backend) | [$apiBase]($apiBase) |
| API health | [$apiBase/health]($apiBase/health) |
| API docs | [$apiBase/docs]($apiBase/docs) |
| Optional local web | [$webBase]($webBase) |

## Vercel environment (required when IP changes)

Set these on Vercel, then **Redeploy**:

``````
NEXT_PUBLIC_API_USE_DIRECT=true
NEXT_PUBLIC_API_BASE_URL=$apiBase
``````

Copy-friendly file: ``Docs/vercel-lan.env.txt``

## Same Wi‑Fi checklist

1. Run ``scripts/start-lan-server.ps1`` so API listens on ``0.0.0.0:$ApiPort``.
2. Update Vercel env if DHCP changed the IP, then redeploy.
3. Teammates open **$VercelOrigin/queries** while on the same Wi‑Fi as this PC.
4. From another device, confirm ``$apiBase/health`` returns ok.

## PC CORS snapshot

``````
$corsOrigins
``````
"@

Set-Content -Path $statusPath -Value $status -Encoding UTF8

Write-Host "LAN IP:     $lanIp"
Write-Host "Vercel UI:  $VercelOrigin/queries"
Write-Host "PC API:     $apiBase"
Write-Host "Vercel env: $vercelEnvPath"
Write-Host "Status:     $statusPath"
